# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartEyes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smartEyes.proto',
  package='smartEyes',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsmartEyes.proto\x12\tsmartEyes\"3\n\x10ListRulesRequest\x12\x1f\n\x05\x63hain\x18\x01 \x01(\x0e\x32\x10.smartEyes.Chain\"\xdf\x01\n\x04Rule\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12!\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x11.smartEyes.Action\x12\x1f\n\x05\x63hain\x18\x03 \x01(\x0e\x32\x10.smartEyes.Chain\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x13\n\x0bsource_cidr\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x65stination\x18\x06 \x01(\t\x12\x18\n\x10\x64\x65stination_cidr\x18\x07 \x01(\x05\x12\r\n\x05\x64port\x18\x08 \x01(\x05\x12\r\n\x05sport\x18\t \x01(\x05\x12\x10\n\x08protocol\x18\n \x01(\t\")\n\x07RuleSet\x12\x1e\n\x05rules\x18\x01 \x03(\x0b\x32\x0f.smartEyes.Rule\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty*+\n\x05\x43hain\x12\t\n\x05INPUT\x10\x00\x12\n\n\x06OUTPUT\x10\x01\x12\x0b\n\x07\x46ORWARD\x10\x02*\x1e\n\x06\x41\x63tion\x12\n\n\x06\x41\x43\x43\x45PT\x10\x00\x12\x08\n\x04\x44ROP\x10\x01\x32\x8f\x02\n\x0cSmartEyesRPC\x12>\n\tListRules\x12\x1b.smartEyes.ListRulesRequest\x1a\x12.smartEyes.RuleSet\"\x00\x12\x36\n\x05\x46lush\x12\x10.smartEyes.Empty\x1a\x19.smartEyes.StringResponse\"\x00\x12\x43\n\x12StartPacketHandler\x12\x10.smartEyes.Empty\x1a\x19.smartEyes.StringResponse\"\x00\x12\x42\n\x11StopPacketHandler\x12\x10.smartEyes.Empty\x1a\x19.smartEyes.StringResponse\"\x00\x62\x06proto3'
)

_CHAIN = _descriptor.EnumDescriptor(
  name='Chain',
  full_name='smartEyes.Chain',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INPUT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=396,
  serialized_end=439,
)
_sym_db.RegisterEnumDescriptor(_CHAIN)

Chain = enum_type_wrapper.EnumTypeWrapper(_CHAIN)
_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='smartEyes.Action',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DROP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=441,
  serialized_end=471,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
INPUT = 0
OUTPUT = 1
FORWARD = 2
ACCEPT = 0
DROP = 1



_LISTRULESREQUEST = _descriptor.Descriptor(
  name='ListRulesRequest',
  full_name='smartEyes.ListRulesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain', full_name='smartEyes.ListRulesRequest.chain', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='smartEyes.Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rule_id', full_name='smartEyes.Rule.rule_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='smartEyes.Rule.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain', full_name='smartEyes.Rule.chain', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='smartEyes.Rule.source', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_cidr', full_name='smartEyes.Rule.source_cidr', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination', full_name='smartEyes.Rule.destination', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination_cidr', full_name='smartEyes.Rule.destination_cidr', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dport', full_name='smartEyes.Rule.dport', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sport', full_name='smartEyes.Rule.sport', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='smartEyes.Rule.protocol', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=307,
)


_RULESET = _descriptor.Descriptor(
  name='RuleSet',
  full_name='smartEyes.RuleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='smartEyes.RuleSet.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=350,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='smartEyes.StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='smartEyes.StringResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=385,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='smartEyes.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=394,
)

_LISTRULESREQUEST.fields_by_name['chain'].enum_type = _CHAIN
_RULE.fields_by_name['action'].enum_type = _ACTION
_RULE.fields_by_name['chain'].enum_type = _CHAIN
_RULESET.fields_by_name['rules'].message_type = _RULE
DESCRIPTOR.message_types_by_name['ListRulesRequest'] = _LISTRULESREQUEST
DESCRIPTOR.message_types_by_name['Rule'] = _RULE
DESCRIPTOR.message_types_by_name['RuleSet'] = _RULESET
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.enum_types_by_name['Chain'] = _CHAIN
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListRulesRequest = _reflection.GeneratedProtocolMessageType('ListRulesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTRULESREQUEST,
  '__module__' : 'smartEyes_pb2'
  # @@protoc_insertion_point(class_scope:smartEyes.ListRulesRequest)
  })
_sym_db.RegisterMessage(ListRulesRequest)

Rule = _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), {
  'DESCRIPTOR' : _RULE,
  '__module__' : 'smartEyes_pb2'
  # @@protoc_insertion_point(class_scope:smartEyes.Rule)
  })
_sym_db.RegisterMessage(Rule)

RuleSet = _reflection.GeneratedProtocolMessageType('RuleSet', (_message.Message,), {
  'DESCRIPTOR' : _RULESET,
  '__module__' : 'smartEyes_pb2'
  # @@protoc_insertion_point(class_scope:smartEyes.RuleSet)
  })
_sym_db.RegisterMessage(RuleSet)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), {
  'DESCRIPTOR' : _STRINGRESPONSE,
  '__module__' : 'smartEyes_pb2'
  # @@protoc_insertion_point(class_scope:smartEyes.StringResponse)
  })
_sym_db.RegisterMessage(StringResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'smartEyes_pb2'
  # @@protoc_insertion_point(class_scope:smartEyes.Empty)
  })
_sym_db.RegisterMessage(Empty)



_SMARTEYESRPC = _descriptor.ServiceDescriptor(
  name='SmartEyesRPC',
  full_name='smartEyes.SmartEyesRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=474,
  serialized_end=745,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListRules',
    full_name='smartEyes.SmartEyesRPC.ListRules',
    index=0,
    containing_service=None,
    input_type=_LISTRULESREQUEST,
    output_type=_RULESET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Flush',
    full_name='smartEyes.SmartEyesRPC.Flush',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartPacketHandler',
    full_name='smartEyes.SmartEyesRPC.StartPacketHandler',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopPacketHandler',
    full_name='smartEyes.SmartEyesRPC.StopPacketHandler',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMARTEYESRPC)

DESCRIPTOR.services_by_name['SmartEyesRPC'] = _SMARTEYESRPC

# @@protoc_insertion_point(module_scope)
